using Come.Models;

namespace Come.Services;

public sealed class PartCatalogService : IPartCatalogService
{
    private readonly IReadOnlyList<PartItem> _parts =
    [
        new() { Id="cpu-7800x3d", Category=PartCategory.Cpu, Name="Ryzen 7 7800X3D", Manufacturer="AMD", Price=529000, Stock=18, SpecSummary="8코어 16스레드 · 최대 5.0GHz", DetailSummary="게이밍에 최적화된 3D V-Cache 데스크톱 프로세서", Accent="#FF6B57", Glyph="R7", PowerConsumptionW=120, Popularity=99, Performance=94, Socket="AM5", Tags=["CPU","AM5","게이밍","고사양"], Specifications=Specs(("소켓","AM5"),("코어 / 스레드","8 / 16"),("최대 클럭","5.0 GHz"),("L3 캐시","96 MB"),("TDP","120 W")) },
        new() { Id="cpu-14700k", Category=PartCategory.Cpu, Name="Core i7-14700K", Manufacturer="Intel", Price=589000, Stock=12, SpecSummary="20코어 28스레드 · 최대 5.6GHz", DetailSummary="게임과 콘텐츠 제작을 모두 잡은 하이브리드 프로세서", Accent="#4E8CFF", Glyph="i7", PowerConsumptionW=253, Popularity=92, Performance=97, Socket="LGA1700", Tags=["CPU","LGA1700","영상편집","고사양"], Specifications=Specs(("소켓","LGA1700"),("코어 / 스레드","20 / 28"),("최대 클럭","5.6 GHz"),("스마트 캐시","33 MB"),("최대 터보 전력","253 W")) },
        new() { Id="cpu-7600", Category=PartCategory.Cpu, Name="Ryzen 5 7600", Manufacturer="AMD", Price=269000, Stock=31, SpecSummary="6코어 12스레드 · 최대 5.1GHz", DetailSummary="낮은 전력과 탄탄한 성능을 갖춘 균형형 프로세서", Accent="#FF826E", Glyph="R5", PowerConsumptionW=65, Popularity=90, Performance=80, Socket="AM5", Tags=["CPU","AM5","가성비","저소음"], Specifications=Specs(("소켓","AM5"),("코어 / 스레드","6 / 12"),("최대 클럭","5.1 GHz"),("L3 캐시","32 MB"),("TDP","65 W")) },

        new() { Id="mb-b650", Category=PartCategory.Mainboard, Name="ROG STRIX B650E-F", Manufacturer="ASUS", Price=389000, Stock=9, SpecSummary="AM5 · DDR5 · ATX", DetailSummary="PCIe 5.0과 Wi-Fi 6E를 지원하는 프리미엄 게이밍 보드", Accent="#B56CFF", Glyph="MB", PowerConsumptionW=55, Popularity=94, Performance=91, Socket="AM5", RamType="DDR5", FormFactor="ATX", Tags=["메인보드","AM5","DDR5","ATX","게이밍"], Specifications=Specs(("소켓","AM5"),("메모리","DDR5 6400+"),("폼팩터","ATX"),("M.2 슬롯","3개"),("무선","Wi-Fi 6E")) },
        new() { Id="mb-b760", Category=PartCategory.Mainboard, Name="MAG B760M MORTAR II", Manufacturer="MSI", Price=249000, Stock=16, SpecSummary="LGA1700 · DDR5 · mATX", DetailSummary="14세대 인텔 CPU와 고속 DDR5를 지원하는 컴팩트 보드", Accent="#8E73FF", Glyph="MB", PowerConsumptionW=50, Popularity=88, Performance=84, Socket="LGA1700", RamType="DDR5", FormFactor="mATX", Tags=["메인보드","LGA1700","DDR5","mATX","가성비"], Specifications=Specs(("소켓","LGA1700"),("메모리","DDR5 7800+"),("폼팩터","mATX"),("M.2 슬롯","3개"),("LAN","2.5 GbE")) },
        new() { Id="mb-a620", Category=PartCategory.Mainboard, Name="TUF GAMING A620M-PLUS", Manufacturer="ASUS", Price=179000, Stock=22, SpecSummary="AM5 · DDR5 · mATX", DetailSummary="필수 기능에 집중한 내구성 높은 AM5 메인보드", Accent="#9C7CFF", Glyph="MB", PowerConsumptionW=45, Popularity=79, Performance=72, Socket="AM5", RamType="DDR5", FormFactor="mATX", Tags=["메인보드","AM5","DDR5","mATX","가성비"], Specifications=Specs(("소켓","AM5"),("메모리","DDR5 6400+"),("폼팩터","mATX"),("M.2 슬롯","2개"),("LAN","2.5 GbE")) },

        new() { Id="ram-6000-32", Category=PartCategory.Memory, Name="Trident Z5 Neo RGB 32GB", Manufacturer="G.SKILL", Price=169000, Stock=27, SpecSummary="DDR5 · 6000MHz · 16GB × 2", DetailSummary="AMD EXPO 기반의 고성능 RGB 메모리 키트", Accent="#36D5C8", Glyph="RAM", PowerConsumptionW=10, Popularity=96, Performance=92, RamType="DDR5", Tags=["RAM","DDR5","게이밍","RGB"], Specifications=Specs(("규격","DDR5"),("용량","32 GB (16×2)"),("속도","6000 MHz"),("타이밍","CL30"),("프로파일","AMD EXPO")) },
        new() { Id="ram-5600-32", Category=PartCategory.Memory, Name="Fury Beast 32GB", Manufacturer="Kingston", Price=129000, Stock=41, SpecSummary="DDR5 · 5600MHz · 16GB × 2", DetailSummary="안정성과 가격 균형이 좋은 로우 프로파일 메모리", Accent="#49C8B7", Glyph="RAM", PowerConsumptionW=10, Popularity=87, Performance=82, RamType="DDR5", Tags=["RAM","DDR5","가성비","저소음"], Specifications=Specs(("규격","DDR5"),("용량","32 GB (16×2)"),("속도","5600 MHz"),("타이밍","CL36"),("프로파일","XMP 3.0")) },
        new() { Id="ram-3600-32", Category=PartCategory.Memory, Name="Vengeance LPX 32GB", Manufacturer="Corsair", Price=99000, Stock=14, SpecSummary="DDR4 · 3600MHz · 16GB × 2", DetailSummary="검증된 호환성의 저소음 DDR4 메모리", Accent="#43BDAF", Glyph="RAM", PowerConsumptionW=9, Popularity=80, Performance=68, RamType="DDR4", Tags=["RAM","DDR4","가성비","저소음"], Specifications=Specs(("규격","DDR4"),("용량","32 GB (16×2)"),("속도","3600 MHz"),("타이밍","CL18"),("프로파일","XMP 2.0")) },

        new() { Id="gpu-4070s", Category=PartCategory.Graphics, Name="GeForce RTX 4070 SUPER", Manufacturer="GIGABYTE", Price=989000, Stock=8, SpecSummary="12GB GDDR6X · 261mm · 220W", DetailSummary="QHD 고주사율 게이밍과 레이 트레이싱을 위한 추천 GPU", Accent="#73E16C", Glyph="GPU", PowerConsumptionW=220, Popularity=98, Performance=91, LengthMm=261, Tags=["GPU","게이밍","고사양","DLSS"], Specifications=Specs(("메모리","12 GB GDDR6X"),("부스트 클럭","2,565 MHz"),("길이","261 mm"),("권장 파워","700 W"),("출력","HDMI 2.1 / DP 1.4a")) },
        new() { Id="gpu-7800xt", Category=PartCategory.Graphics, Name="Radeon RX 7800 XT NITRO+", Manufacturer="SAPPHIRE", Price=829000, Stock=11, SpecSummary="16GB GDDR6 · 320mm · 263W", DetailSummary="넉넉한 VRAM과 강력한 QHD 래스터 성능의 그래픽카드", Accent="#7CEB78", Glyph="GPU", PowerConsumptionW=263, Popularity=89, Performance=90, LengthMm=320, Tags=["GPU","게이밍","고사양","가성비"], Specifications=Specs(("메모리","16 GB GDDR6"),("게임 클럭","2,254 MHz"),("길이","320 mm"),("권장 파워","700 W"),("출력","HDMI 2.1 / DP 2.1")) },
        new() { Id="gpu-4060", Category=PartCategory.Graphics, Name="GeForce RTX 4060 Twin Edge", Manufacturer="ZOTAC", Price=449000, Stock=25, SpecSummary="8GB GDDR6 · 221mm · 115W", DetailSummary="전력 효율이 뛰어난 FHD 게이밍 그래픽카드", Accent="#65D960", Glyph="GPU", PowerConsumptionW=115, Popularity=86, Performance=73, LengthMm=221, Tags=["GPU","게이밍","가성비","저전력"], Specifications=Specs(("메모리","8 GB GDDR6"),("부스트 클럭","2,460 MHz"),("길이","221 mm"),("권장 파워","500 W"),("출력","HDMI 2.1 / DP 1.4a")) },

        new() { Id="ssd-990-2t", Category=PartCategory.Storage, Name="990 PRO 2TB", Manufacturer="Samsung", Price=239000, Stock=35, SpecSummary="NVMe PCIe 4.0 · 읽기 7,450MB/s", DetailSummary="대용량 작업과 게임 로딩에 최적화된 플래그십 SSD", Accent="#FFB84D", Glyph="SSD", PowerConsumptionW=9, Popularity=97, Performance=96, Tags=["SSD","NVMe","고사양","영상편집"], Specifications=Specs(("인터페이스","PCIe 4.0 NVMe"),("용량","2 TB"),("순차 읽기","7,450 MB/s"),("순차 쓰기","6,900 MB/s"),("보증","5년")) },
        new() { Id="ssd-p3-1t", Category=PartCategory.Storage, Name="P3 Plus 1TB", Manufacturer="Crucial", Price=89000, Stock=56, SpecSummary="NVMe PCIe 4.0 · 읽기 5,000MB/s", DetailSummary="일상 작업과 게임에 충분한 가성비 NVMe SSD", Accent="#F3A83D", Glyph="SSD", PowerConsumptionW=7, Popularity=91, Performance=75, Tags=["SSD","NVMe","가성비"], Specifications=Specs(("인터페이스","PCIe 4.0 NVMe"),("용량","1 TB"),("순차 읽기","5,000 MB/s"),("순차 쓰기","3,600 MB/s"),("보증","5년")) },
        new() { Id="ssd-sn850x-2t", Category=PartCategory.Storage, Name="WD_BLACK SN850X 2TB", Manufacturer="Western Digital", Price=219000, Stock=19, SpecSummary="NVMe PCIe 4.0 · 읽기 7,300MB/s", DetailSummary="게임 모드와 낮은 지연시간을 갖춘 고성능 SSD", Accent="#FFC25E", Glyph="SSD", PowerConsumptionW=8, Popularity=90, Performance=93, Tags=["SSD","NVMe","게이밍","고사양"], Specifications=Specs(("인터페이스","PCIe 4.0 NVMe"),("용량","2 TB"),("순차 읽기","7,300 MB/s"),("순차 쓰기","6,600 MB/s"),("보증","5년")) },

        new() { Id="psu-850", Category=PartCategory.Power, Name="RM850x SHIFT", Manufacturer="Corsair", Price=229000, Stock=15, SpecSummary="850W · 80 PLUS Gold · ATX 3.0", DetailSummary="측면 커넥터와 저소음 팬을 적용한 고효율 파워", Accent="#F6C95C", Glyph="PSU", PowerConsumptionW=0, Popularity=94, Performance=92, Wattage=850, Tags=["파워","850W","골드","저소음"], Specifications=Specs(("정격 출력","850 W"),("효율","80 PLUS Gold"),("규격","ATX 3.0"),("모듈러","풀 모듈러"),("보증","10년")) },
        new() { Id="psu-750", Category=PartCategory.Power, Name="SuperNOVA 750 GT", Manufacturer="EVGA", Price=159000, Stock=28, SpecSummary="750W · 80 PLUS Gold · 풀 모듈러", DetailSummary="안정적인 출력과 합리적 가격의 게이밍 파워", Accent="#EFC04E", Glyph="PSU", PowerConsumptionW=0, Popularity=87, Performance=84, Wattage=750, Tags=["파워","750W","골드","가성비"], Specifications=Specs(("정격 출력","750 W"),("효율","80 PLUS Gold"),("규격","ATX"),("모듈러","풀 모듈러"),("보증","7년")) },
        new() { Id="psu-650", Category=PartCategory.Power, Name="MWE Gold 650 V2", Manufacturer="Cooler Master", Price=119000, Stock=34, SpecSummary="650W · 80 PLUS Gold · 풀 모듈러", DetailSummary="중급 시스템에 어울리는 컴팩트 고효율 파워", Accent="#E3B74E", Glyph="PSU", PowerConsumptionW=0, Popularity=82, Performance=76, Wattage=650, Tags=["파워","650W","골드","가성비"], Specifications=Specs(("정격 출력","650 W"),("효율","80 PLUS Gold"),("규격","ATX"),("모듈러","풀 모듈러"),("보증","5년")) },

        new() { Id="case-north", Category=PartCategory.Case, Name="North Charcoal TG", Manufacturer="Fractal Design", Price=219000, Stock=7, SpecSummary="ATX · GPU 355mm · 쿨러 170mm", DetailSummary="천연 우드 전면과 뛰어난 통풍을 결합한 미들타워", Accent="#C98B64", Glyph="CASE", PowerConsumptionW=5, Popularity=98, Performance=91, SupportedFormFactors=["ATX","mATX","ITX"], MaxGpuLengthMm=355, MaxCoolerHeightMm=170, Tags=["케이스","ATX","저소음","디자인"], Specifications=Specs(("지원 보드","ATX / mATX / ITX"),("GPU 길이","최대 355 mm"),("쿨러 높이","최대 170 mm"),("기본 팬","140 mm × 2"),("측면","강화유리")) },
        new() { Id="case-h5", Category=PartCategory.Case, Name="H5 Flow RGB", Manufacturer="NZXT", Price=159000, Stock=18, SpecSummary="ATX · GPU 365mm · 쿨러 165mm", DetailSummary="깔끔한 외형과 집중 냉각 구조의 RGB 미들타워", Accent="#D49B79", Glyph="CASE", PowerConsumptionW=8, Popularity=92, Performance=88, SupportedFormFactors=["ATX","mATX","ITX"], MaxGpuLengthMm=365, MaxCoolerHeightMm=165, Tags=["케이스","ATX","게이밍","RGB"], Specifications=Specs(("지원 보드","ATX / mATX / ITX"),("GPU 길이","최대 365 mm"),("쿨러 높이","최대 165 mm"),("기본 팬","120 mm × 4"),("측면","강화유리")) },
        new() { Id="case-nr200", Category=PartCategory.Case, Name="NR200P MAX", Manufacturer="Cooler Master", Price=439000, Stock=5, SpecSummary="ITX · GPU 336mm · 수랭 280mm", DetailSummary="파워와 수랭 쿨러가 포함된 고성능 미니 ITX 케이스", Accent="#BE815D", Glyph="CASE", PowerConsumptionW=5, Popularity=84, Performance=85, SupportedFormFactors=["ITX"], MaxGpuLengthMm=336, MaxCoolerHeightMm=67, Tags=["케이스","ITX","컴팩트","고사양"], Specifications=Specs(("지원 보드","ITX"),("GPU 길이","최대 336 mm"),("공랭 높이","최대 67 mm"),("기본 수랭","280 mm"),("포함 파워","850 W Gold")) },

        new() { Id="cooler-pa120", Category=PartCategory.Cooler, Name="Peerless Assassin 120 SE", Manufacturer="Thermalright", Price=59000, Stock=44, SpecSummary="듀얼 타워 · 높이 155mm · 2팬", DetailSummary="가격 대비 탁월한 냉각 성능의 듀얼 타워 공랭 쿨러", Accent="#5BB8FF", Glyph="FAN", PowerConsumptionW=6, Popularity=99, Performance=87, HeightMm=155, Tags=["쿨러","공랭","가성비","저소음"], Specifications=Specs(("방식","듀얼 타워 공랭"),("높이","155 mm"),("팬","120 mm × 2"),("소음","25.6 dBA"),("소켓","AM5 / LGA1700")) },
        new() { Id="cooler-nh", Category=PartCategory.Cooler, Name="NH-D15 chromax.black", Manufacturer="Noctua", Price=159000, Stock=13, SpecSummary="듀얼 타워 · 높이 165mm · 2팬", DetailSummary="검증된 냉각력과 정숙성을 갖춘 프리미엄 공랭 쿨러", Accent="#74C5FF", Glyph="FAN", PowerConsumptionW=5, Popularity=91, Performance=94, HeightMm=165, Tags=["쿨러","공랭","고사양","저소음"], Specifications=Specs(("방식","듀얼 타워 공랭"),("높이","165 mm"),("팬","140 mm × 2"),("소음","24.6 dBA"),("보증","6년")) },
        new() { Id="cooler-ls720", Category=PartCategory.Cooler, Name="LS720 SE Digital", Manufacturer="DeepCool", Price=149000, Stock=20, SpecSummary="360mm 수랭 · 디지털 헤드 · 3팬", DetailSummary="CPU 상태 표시와 강력한 냉각 성능을 갖춘 일체형 수랭", Accent="#4BAFF4", Glyph="AIO", PowerConsumptionW=12, Popularity=89, Performance=97, HeightMm=55, Tags=["쿨러","수랭","고사양","RGB"], Specifications=Specs(("방식","360 mm 일체형 수랭"),("라디에이터","402 × 120 mm"),("팬","120 mm × 3"),("펌프 속도","3,100 RPM"),("소켓","AM5 / LGA1700")) },
    ];

    public IReadOnlyList<PartItem> GetAll() => _parts;

    private static IReadOnlyDictionary<string, string> Specs(params (string Key, string Value)[] values) =>
        values.ToDictionary(item => item.Key, item => item.Value);
}
